---
title: eDNA reads, AVSs, and species
output: md_document
editor_options: 
  chunk_output_type: console
---

# eDNA data exploration

```{r setup, include=FALSE}
knitr::opts_chunk$set(dpi=300)
```

## Read dataset

```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(purrr)
library(stringr)

dna_files <- list.files("../output", "*DNADerivedData*", full.names = TRUE)
occurrence_files <- list.files("../output", "*Occurrence*", full.names = TRUE)

dna <- map(dna_files, read.table, sep = "\t", quote = "", header = TRUE) %>%
  bind_rows() %>%
  mutate_if(is.character, na_if, "")

occurrence <- map(occurrence_files, read.table, sep = "\t", quote = "", header = TRUE) %>%
  bind_rows() %>%
  mutate_if(is.character, na_if, "") %>%
  mutate(species = ifelse(taxonRank == "species", scientificName, NA)) %>%
  left_join(dna, by = "occurrenceID")
```

## Reads, AVSs, and species by marker

```{r message=FALSE, warning=FALSE, fig.width=10, fig.height=5}
stats <- occurrence %>%
  filter(str_detect(materialSampleID, "EE")) %>%
  group_by(higherGeography, materialSampleID, pcr_primer_name_forward) %>%
  summarize(species = n_distinct(species, na.rm = TRUE), asvs = n(), reads = sum(organismQuantity))
```

### Linear

```{r message=FALSE, warning=FALSE, fig.width=10, fig.height=5}
ggplot() +
  geom_point(data = stats, aes(reads, asvs, color = pcr_primer_name_forward)) +
  stat_smooth(data = stats, aes(reads, asvs, color = pcr_primer_name_forward), method = "lm", geom = "smooth", formula = (y ~ x)) +
  theme_minimal() +
  ggtitle("ASVs by reads")

ggplot() +
  geom_point(data = stats, aes(reads, species, color = pcr_primer_name_forward)) +
  stat_smooth(data = stats, aes(reads, species, color = pcr_primer_name_forward), method = "lm", geom = "smooth", formula = (y ~ x)) +
  theme_minimal() +
  ggtitle("Species by reads")

ggplot() +
  geom_point(data = stats, aes(asvs, species, color = pcr_primer_name_forward)) +
  stat_smooth(data = stats, aes(asvs, species, color = pcr_primer_name_forward), method = "lm", geom = "smooth", formula = (y ~ x)) +
  theme_minimal() +
  ggtitle("Species by ASVs")
```

### Linear by site and marker

```{r}
ggplot() +
  geom_point(data = stats, aes(reads, species, shape = higherGeography, color = pcr_primer_name_forward)) +
  stat_smooth(data = stats, aes(reads, species, shape = higherGeography, color = pcr_primer_name_forward), method = "lm", geom = "smooth", formula = (y ~ x), se = FALSE) +
  theme_minimal() +
  ggtitle("Species by reads") +
  scale_shape_manual(values = 0:15)
```

### Local polynomial

```{r message=FALSE, warning=FALSE, fig.width=10, fig.height=5}
ggplot() +
  geom_point(data = stats, aes(reads, asvs, color = pcr_primer_name_forward)) +
  stat_smooth(data = stats, aes(reads, asvs, color = pcr_primer_name_forward), method = "loess", geom = "smooth", formula = (y ~ x)) +
  theme_minimal() +
  ggtitle("ASVs by reads")

ggplot() +
  geom_point(data = stats, aes(reads, species, color = pcr_primer_name_forward)) +
  stat_smooth(data = stats, aes(reads, species, color = pcr_primer_name_forward), method = "loess", geom = "smooth", formula = (y ~ x)) +
  theme_minimal() +
  ggtitle("Species by reads")

ggplot() +
  geom_point(data = stats, aes(asvs, species, color = pcr_primer_name_forward)) +
  stat_smooth(data = stats, aes(asvs, species, color = pcr_primer_name_forward), method = "loess", geom = "smooth", formula = (y ~ x)) +
  theme_minimal() +
  ggtitle("Species by ASVs")
```

## Rarefaction curves

To do.
