name: Generate Data

on:
  workflow_dispatch:

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: List files
        run: ls -al
      - name: Generate data
        run: python index.py
      - name: Commit data
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b data
          mv output data
          git add data
          git commit -m "Update data"
          git push --force origin data
